<?xml version="1.0" ?>
<testsuite errors="7" failures="0" name="CheckOpiFormat-20171122170825" tests="10" time="0.010">
	<testcase classname="CheckOpiFormat" name="test_GIVEN_a_label_outside_a_grouping_container_THEN_it_is_title_case" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_a_push_button_THEN_it_is_within_a_grouping_container" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_labels_WHEN_checking_the_background_colour_THEN_it_is_the_isis_background" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_a_label_THEN_it_ends_in_a_colon" time="0.000">
		<error message="Label on line 84 with text 'X Axis' did not end in a colon.
Label on line 207 with text 'Y Axis' did not end in a colon.
Label on line 248 with text 'Z Axis' did not end in a colon.
Label on line 289 with text 'Magnitude' did not end in a colon.
Label on line 381 with text 'Theta' did not end in a colon.
Label on line 473 with text 'Phi' did not end in a colon.
Label on line 1100 with text 'Units' did not end in a colon.
Label on line 2152 with text 'X Axis' did not end in a colon.
Label on line 2193 with text 'Y Axis' did not end in a colon.
Label on line 2234 with text 'Z Axis' did not end in a colon.
Label on line 2544 with text 'X Axis' did not end in a colon.
Label on line 2732 with text 'Y Axis' did not end in a colon.
Label on line 2826 with text 'Z Axis' did not end in a colon.
Label on line 3325 with text 'HX' did not end in a colon.
Label on line 3458 with text 'Sample' did not end in a colon." type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "check_opi_format.py", line 224, in test_GIVEN_a_label_THEN_it_ends_in_a_colon
    self.fail(message)
AssertionError: Label on line 84 with text 'X Axis' did not end in a colon.
Label on line 207 with text 'Y Axis' did not end in a colon.
Label on line 248 with text 'Z Axis' did not end in a colon.
Label on line 289 with text 'Magnitude' did not end in a colon.
Label on line 381 with text 'Theta' did not end in a colon.
Label on line 473 with text 'Phi' did not end in a colon.
Label on line 1100 with text 'Units' did not end in a colon.
Label on line 2152 with text 'X Axis' did not end in a colon.
Label on line 2193 with text 'Y Axis' did not end in a colon.
Label on line 2234 with text 'Z Axis' did not end in a colon.
Label on line 2544 with text 'X Axis' did not end in a colon.
Label on line 2732 with text 'Y Axis' did not end in a colon.
Label on line 2826 with text 'Z Axis' did not end in a colon.
Label on line 3325 with text 'HX' did not end in a colon.
Label on line 3458 with text 'Sample' did not end in a colon.
]]>		</error>
	</testcase>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_a_label_within_a_grouping_container_THEN_it_is_sentence_case" time="0.000">
		<error message="Label on line 84: X Axis
Label on line 207: Y Axis
Label on line 248: Z Axis
Label on line 1294: Set Point:
Label on line 2152: X Axis
Label on line 2193: Y Axis
Label on line 2234: Z Axis
Label on line 2544: X Axis
Label on line 2732: Y Axis
Label on line 2826: Z Axis
Label on line 3325: HX
Label on line 3499: Set Point:
Label on line 4301: ANV position:
Label on line 4581: Level Mode:" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "check_opi_format.py", line 231, in test_GIVEN_a_label_within_a_grouping_container_THEN_it_is_sentence_case
    self.fail(message)
AssertionError: Label on line 84: X Axis
Label on line 207: Y Axis
Label on line 248: Z Axis
Label on line 1294: Set Point:
Label on line 2152: X Axis
Label on line 2193: Y Axis
Label on line 2234: Z Axis
Label on line 2544: X Axis
Label on line 2732: Y Axis
Label on line 2826: Z Axis
Label on line 3325: HX
Label on line 3499: Set Point:
Label on line 4301: ANV position:
Label on line 4581: Level Mode:
]]>		</error>
	</testcase>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_grouping_containers_WHEN_checking_the_background_colour_THEN_it_is_the_isis_background" time="0.000">
		<error message="On line 2468, text 'Grouping Container_2', colour was not correct." type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "check_opi_format.py", line 202, in test_GIVEN_an_opi_file_with_grouping_containers_WHEN_checking_the_background_colour_THEN_it_is_the_isis_background
    self._assert_colour_correct("background_color", "groupingContainer", ["ISIS_OPI_Background"])
  File "check_opi_format.py", line 199, in _assert_colour_correct
    self.fail("\n".join(["On line {}, text '{}', colour was not correct.".format(*error) for error in errors]))
AssertionError: On line 2468, text 'Grouping Container_2', colour was not correct.
]]>		</error>
	</testcase>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_led_WHEN_checking_off_colour_THEN_it_is_the_isis_led_off_colour" time="0.000">
		<error message="On line 2513, text 'LED', colour was not correct.
On line 2701, text 'LED_1', colour was not correct.
On line 2795, text 'LED_2', colour was not correct." type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "check_opi_format.py", line 217, in test_GIVEN_an_opi_file_with_led_WHEN_checking_off_colour_THEN_it_is_the_isis_led_off_colour
    self._assert_colour_correct("off_color", "LED", ["ISIS_Green_LED_Off", "ISIS_Red_LED_Off"])
  File "check_opi_format.py", line 199, in _assert_colour_correct
    self.fail("\n".join(["On line {}, text '{}', colour was not correct.".format(*error) for error in errors]))
AssertionError: On line 2513, text 'LED', colour was not correct.
On line 2701, text 'LED_1', colour was not correct.
On line 2795, text 'LED_2', colour was not correct.
]]>		</error>
	</testcase>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_led_WHEN_checking_on_colour_THEN_it_is_the_isis_led_on_colour" time="0.010">
		<error message="On line 2493, text 'LED', colour was not correct.
On line 2681, text 'LED_1', colour was not correct.
On line 2775, text 'LED_2', colour was not correct." type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "check_opi_format.py", line 214, in test_GIVEN_an_opi_file_with_led_WHEN_checking_on_colour_THEN_it_is_the_isis_led_on_colour
    self._assert_colour_correct("on_color", "LED", ["ISIS_Green_LED_On", "ISIS_Red_LED_On"])
  File "check_opi_format.py", line 199, in _assert_colour_correct
    self.fail("\n".join(["On line {}, text '{}', colour was not correct.".format(*error) for error in errors]))
AssertionError: On line 2493, text 'LED', colour was not correct.
On line 2681, text 'LED_1', colour was not correct.
On line 2775, text 'LED_2', colour was not correct.
]]>		</error>
	</testcase>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_textbox_WHEN_checking_background_colour_THEN_it_is_the_isis_textbox_background" time="0.000">
		<error message="On line 944, text 'None', colour was not correct.
On line 1368, text 'None', colour was not correct.
On line 1424, text 'None', colour was not correct.
On line 1480, text 'None', colour was not correct.
On line 1679, text 'None', colour was not correct.
On line 1837, text 'None', colour was not correct.
On line 3261, text 'None', colour was not correct.
On line 3941, text 'None', colour was not correct.
On line 4426, text 'None', colour was not correct." type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "check_opi_format.py", line 208, in test_GIVEN_an_opi_file_with_textbox_WHEN_checking_background_colour_THEN_it_is_the_isis_textbox_background
    self._assert_colour_correct("background_color", "TextInput", ["ISIS_Textbox_Background"])
  File "check_opi_format.py", line 199, in _assert_colour_correct
    self.fail("\n".join(["On line {}, text '{}', colour was not correct.".format(*error) for error in errors]))
AssertionError: On line 944, text 'None', colour was not correct.
On line 1368, text 'None', colour was not correct.
On line 1424, text 'None', colour was not correct.
On line 1480, text 'None', colour was not correct.
On line 1679, text 'None', colour was not correct.
On line 1837, text 'None', colour was not correct.
On line 3261, text 'None', colour was not correct.
On line 3941, text 'None', colour was not correct.
On line 4426, text 'None', colour was not correct.
]]>		</error>
	</testcase>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_textbox_WHEN_checking_foreground_colour_THEN_it_is_the_isis_textbox_foreground" time="0.000">
		<error message="On line 951, text 'None', colour was not correct.
On line 1375, text 'None', colour was not correct.
On line 1431, text 'None', colour was not correct.
On line 1487, text 'None', colour was not correct.
On line 1686, text 'None', colour was not correct.
On line 1844, text 'None', colour was not correct.
On line 3268, text 'None', colour was not correct.
On line 3948, text 'None', colour was not correct.
On line 4433, text 'None', colour was not correct." type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "check_opi_format.py", line 211, in test_GIVEN_an_opi_file_with_textbox_WHEN_checking_foreground_colour_THEN_it_is_the_isis_textbox_foreground
    self._assert_colour_correct("foreground_color", "TextInput", ["ISIS_Standard_Text"])
  File "check_opi_format.py", line 199, in _assert_colour_correct
    self.fail("\n".join(["On line {}, text '{}', colour was not correct.".format(*error) for error in errors]))
AssertionError: On line 951, text 'None', colour was not correct.
On line 1375, text 'None', colour was not correct.
On line 1431, text 'None', colour was not correct.
On line 1487, text 'None', colour was not correct.
On line 1686, text 'None', colour was not correct.
On line 1844, text 'None', colour was not correct.
On line 3268, text 'None', colour was not correct.
On line 3948, text 'None', colour was not correct.
On line 4433, text 'None', colour was not correct.
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
