<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="CheckOpiFormat-20171122111359" tests="6" time="0.000">
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_labels_WHEN_checking_the_background_colour_THEN_it_is_the_isis_background" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_led_WHEN_checking_off_colour_THEN_it_is_the_isis_led_off_colour" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_led_WHEN_checking_on_colour_THEN_it_is_the_isis_led_on_colour" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_textbox_WHEN_checking_background_colour_THEN_it_is_the_isis_textbox_background" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_textbox_WHEN_checking_foreground_colour_THEN_it_is_the_isis_textbox_foreground" time="0.000"/>
	<testcase classname="CheckOpiFormat" name="test_GIVEN_an_opi_file_with_grouping_containers_WHEN_checking_the_background_colour_THEN_it_is_the_isis_background" time="0.000">
		<error message="On line 121, text 'Position', colour was not correct.
On line 1431, text 'Advanced', colour was not correct." type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "check_opi_format.py", line 319, in test_GIVEN_an_opi_file_with_grouping_containers_WHEN_checking_the_background_colour_THEN_it_is_the_isis_background
    self._assert_colour_correct("background_color", "groupingContainer", ["ISIS_OPI_Background"])
  File "check_opi_format.py", line 316, in _assert_colour_correct
    ["On line {}, text '{}', colour was not correct.".format(*error) for error in errors]))
AssertionError: On line 121, text 'Position', colour was not correct.
On line 1431, text 'Advanced', colour was not correct.
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
